spring:
  datasource:
    url:  "jdbc:postgresql://localhost:5432/hrparadise"
    username:  "pguser"
    password:  "1234"
    driver-class-name: "org.postgresql.Driver"
  data:
    jpa.repositories.enabled: true